# Generated by Django 3.2.5 on 2021-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('userlast', models.CharField(default='lastname', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
                ('phno', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('pas', models.CharField(max_length=100)),
                ('cnfpass', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(default='C:\\Users\\vansh\\Downloads\\1.png', upload_to='pics1')),
            ],
        ),
    ]
