# Generated by Django 3.2.5 on 2021-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='img2',
            field=models.ImageField(default='C:\\Users\\vansh\\Downloads\\1.png', upload_to='pics1'),
        ),
    ]
