# Generated by Django 3.2.5 on 2021-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_placeholder_userlast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='userlast',
            field=models.CharField(default='lastname', max_length=100),
        ),
    ]
