# Generated by Django 3.2.5 on 2021-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_placeholder_userlast'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholder',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
